### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by malcolmlewis** [jpwenzel/audio2mp3#1]
Hi
Under what license is the script being released, as would like to package it up for openSUSE.

Perhaps GPL-3.0? You would just need to add a file called COPYING from http://www.gnu.org/licenses/gpl.txt to your repository.

**Comment by jpwenzel** [comment]
Malcolm:

Thanks for your question. I'd love to see the script available for openSUSE.

Let me check if GPLv3 works for this script. In the meantime, I have renamed it from "m4a2mp3" to "audio2mp3" and added more input codecs, but I have not updated the code on github yet. I'll do that in the next days (I'm travelling at the moment) when I have access to my computer at home again.

Best regards,

--JP

**Comment by jpwenzel** [comment]
Added the MIT license for this project.
